kind: pipeline
name: ware-page

trigger:
  branch:
    - master
    - test

steps:

  - name: restore-cache
    image: drillster/drone-volume-cache
    settings:
      restore: true
      mount:
        - ./.npm-cache
        - ./node_modules
    volumes:
      - name: cache
        path: /cache

  - name: npm-install
    image: node:10
    commands:
      - npm config set cache ./.npm-cache --global
      - npm config set registry http://registry.npm.taobao.org/
      - npm install

  - name: npm-build
    image: node:10
    when:
      branch:
        - master
    commands:
      - npm run build-prod

  - name: test-npm-build
    image: node:10
    when:
      branch:
        - test
    commands:
      - npm run build-test


  - name: rebuild-cache
    image: drillster/drone-volume-cache
    settings:
      rebuild: true
      mount:
        - ./.npm-cache
        - ./node_modules
    volumes:
      - name: cache
        path: /cache

  - name: build
    image: plugins/docker
    settings:
      mirror: https://hccwwfjl.mirror.aliyuncs.com/
      registry: swr.cn-north-1.myhuaweicloud.com
      username: cn-north-1@8BKNSGZGCNYMTOUZR9YS
      password: e119c7e6f7a4572454fa96f7b8b6fa34d37a00e7e16caa3274b69c0c6eeded7b
      repo: swr.cn-north-1.myhuaweicloud.com/a82253452/${DRONE_STAGE_NAME}/${DRONE_BRANCH}
      tags: ${DRONE_BUILD_NUMBER}
      build_args:
        - APPDIR=dist

  - name: release
    image: docker:dind
    when:
      branch:
        - master
    environment:
      IMAGE: swr.cn-north-1.myhuaweicloud.com/a82253452/${DRONE_STAGE_NAME}/${DRONE_BRANCH}:${DRONE_BUILD_NUMBER}
      DOMAIN: ware.zhihuizhan.net
      PROFILE: prod
      PORT: 80
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
      - name: registry-auth
        path: /root/.docker
    commands:
      - docker service update --image swr.cn-north-1.myhuaweicloud.com/a82253452/${DRONE_STAGE_NAME}/${DRONE_BRANCH}:${DRONE_BUILD_NUMBER} ${DRONE_STAGE_NAME}-${DRONE_BRANCH}_service --with-registry-auth

  - name: release-failed
    image: docker:dind
    when:
      branch:
        - master
    environment:
      IMAGE: swr.cn-north-1.myhuaweicloud.com/a82253452/${DRONE_STAGE_NAME}/${DRONE_BRANCH}:${DRONE_BUILD_NUMBER}
      DOMAIN: ware.zhihuizhan.net
      PROFILE: prod
      PORT: 80
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
      - name: registry-auth
        path: /root/.docker
    when:
      status:
        - failure
    commands:
      - docker stack deploy -c docker-compose.yml ${DRONE_STAGE_NAME}-${DRONE_BRANCH} --with-registry-auth

  - name: test-release
    image: docker:dind
    when:
      branch:
        - test
    environment:
      IMAGE: swr.cn-north-1.myhuaweicloud.com/a82253452/${DRONE_STAGE_NAME}/${DRONE_BRANCH}:${DRONE_BUILD_NUMBER}
      DOMAIN: test-ware.zhihuizhan.net
      PROFILE: test
      PORT: 80
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
      - name: registry-auth
        path: /root/.docker
    commands:
      - docker service update --image swr.cn-north-1.myhuaweicloud.com/a82253452/${DRONE_STAGE_NAME}/${DRONE_BRANCH}:${DRONE_BUILD_NUMBER} ${DRONE_STAGE_NAME}-${DRONE_BRANCH}_service --with-registry-auth

  - name: test-release-failed
    image: docker:dind
    when:
      branch:
        - test
    environment:
      IMAGE: swr.cn-north-1.myhuaweicloud.com/a82253452/${DRONE_STAGE_NAME}/${DRONE_BRANCH}:${DRONE_BUILD_NUMBER}
      DOMAIN: test-ware.zhihuizhan.net
      PROFILE: test
      PORT: 80
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
      - name: registry-auth
        path: /root/.docker
    when:
      status:
        - failure
    commands:
      - docker stack deploy -c docker-compose.yml ${DRONE_STAGE_NAME}-${DRONE_BRANCH} --with-registry-auth

  - name: dingtalk
    image: lddsb/drone-dingtalk-message
    settings:
      token: https://oapi.dingtalk.com/robot/send?access_token=8231ca915f3e42b623b4a28e0ae6e5ca99861e6553770900eab4be898386cc18
      type: markdown
      message_color: true
      message_pic: true
      sha_link: true
volumes:
  - name: cache
    host:
      path: /tmp/cache
  - name: dockersock
    host:
      path: /var/run/docker.sock
  - name: registry-auth
    host:
      path: /root/.docker
