kind: pipeline
name: ware-page

environment:
  DOMAIN: ware.zhihuizhan.net
  REGISTRY: 192.168.0.2:5000
  PATHPREFIX:
  PROFILE: prod
  APPDIR: dist
  PORT: 80

steps:

  - name: restore-cache
    image: drillster/drone-volume-cache
    settings:
      restore: true
      mount:
        - ./.npm-cache
        - ./node_modules
    volumes:
      - name: cache
        path: /cache

  - name: npm-install
    image: node:10
    commands:
      - npm config set cache ./.npm-cache --global
      - npm config set registry http://registry.npm.taobao.org/
      - npm install && npm run build:$PROFILE

  - name: rebuild-cache
    image: drillster/drone-volume-cache
    settings:
      rebuild: true
      mount:
        - ./.npm-cache
        - ./node_modules
    volumes:
      - name: cache
        path: /cache

  - name: release
    image: docker:dind
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
      - name: registry-auth
        path: /root/.docker
    commands:
      - docker build --rm=true -f Dockerfile -t $REGISTRY/${DRONE_STAGE_NAME}/${DRONE_BRANCH}:${DRONE_BUILD_NUMBER} . --pull=true --build-arg APPDIR=$APPDIR --build-arg PORT=$PORT
      - docker push $REGISTRY/${DRONE_STAGE_NAME}/${DRONE_BRANCH}:${DRONE_BUILD_NUMBER}
      - docker service update --image $REGISTRY/${DRONE_STAGE_NAME}/${DRONE_BRANCH}:${DRONE_BUILD_NUMBER} ${DRONE_STAGE_NAME}-${DRONE_BRANCH}_service --with-registry-auth

  - name: release-failed
    image: docker:dind
    environment:
      IMAGE: $REGISTRY/${DRONE_STAGE_NAME}/${DRONE_BRANCH}:${DRONE_BUILD_NUMBER}
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
      - name: registry-auth
        path: /root/.docker
    when:
      status:
        - failure
    commands:
      - docker stack deploy -c docker-compose.yml ${DRONE_STAGE_NAME}-${DRONE_BRANCH} --with-registry-auth

  - name: dingtalk
    image: lddsb/drone-dingtalk-message
    settings:
      token: https://oapi.dingtalk.com/robot/send?access_token=8231ca915f3e42b623b4a28e0ae6e5ca99861e6553770900eab4be898386cc18
      type: markdown
      message_color: true
      message_pic: true
      sha_link: true
    when:
      status:
        - success
        - failure
trigger:
  branch:
    - master

volumes:
  - name: cache
    host:
      path: /tmp/cache
  - name: dockersock
    host:
      path: /var/run/docker.sock
  - name: registry-auth
    host:
      path: /root/.docker


---
kind: pipeline
name: ware-page-test

environment:
  DOMAIN: test-ware.zhihuizhan.net
  REGISTRY: 192.168.0.2:5000
  PATHPREFIX:
  PROFILE: test
  APPDIR: dist
  PORT: 80

steps:

  - name: restore-cache
    image: drillster/drone-volume-cache
    settings:
      restore: true
      mount:
        - ./.npm-cache
        - ./node_modules
    volumes:
      - name: cache
        path: /cache

  - name: npm-install
    image: node:10
    commands:
      - npm config set cache ./.npm-cache --global
      - npm config set registry http://registry.npm.taobao.org/
      - npm install && npm run build:$PROFILE

  - name: rebuild-cache
    image: drillster/drone-volume-cache
    settings:
      rebuild: true
      mount:
        - ./.npm-cache
        - ./node_modules
    volumes:
      - name: cache
        path: /cache

  - name: release
    image: docker:dind
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
      - name: registry-auth
        path: /root/.docker
    commands:
      - docker build --rm=true -f Dockerfile -t $REGISTRY/${DRONE_STAGE_NAME}/${DRONE_BRANCH}:${DRONE_BUILD_NUMBER} . --pull=true --build-arg APPDIR=$APPDIR --build-arg PORT=$PORT
      - docker push $REGISTRY/${DRONE_STAGE_NAME}/${DRONE_BRANCH}:${DRONE_BUILD_NUMBER}
      - docker service update --image $REGISTRY/${DRONE_STAGE_NAME}/${DRONE_BRANCH}:${DRONE_BUILD_NUMBER} ${DRONE_STAGE_NAME}-${DRONE_BRANCH}_service --with-registry-auth

  - name: release-failed
    image: docker:dind
    environment:
      IMAGE: ${REGISTRY}/${DRONE_STAGE_NAME}/${DRONE_BRANCH}:${DRONE_BUILD_NUMBER}
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
      - name: registry-auth
        path: /root/.docker
    when:
      status:
        - failure
    commands:
      - docker stack deploy -c docker-compose.yml ${DRONE_STAGE_NAME}-${DRONE_BRANCH} --with-registry-auth

  - name: dingtalk
    image: lddsb/drone-dingtalk-message
    settings:
      token: https://oapi.dingtalk.com/robot/send?access_token=8231ca915f3e42b623b4a28e0ae6e5ca99861e6553770900eab4be898386cc18
      type: markdown
      message_color: true
      message_pic: true
      sha_link: true
    when:
      status:
        - success
        - failure

trigger:
  branch:
    - test

volumes:
  - name: cache
    host:
      path: /tmp/cache
  - name: dockersock
    host:
      path: /var/run/docker.sock
  - name: registry-auth
    host:
      path: /root/.docker
