kind: pipeline
name: mass-page

environment:
  DOMAIN: ware.zhihuizhan.net
  PATHPREFIX:
  PROFILE: prod
  APPDIR: dist
  PORT: 80

steps:

  - name: restore-cache
    image: drillster/drone-volume-cache
    settings:
      restore: true
      mount:
        - ./.npm-cache
        - ./node_modules
    volumes:
      - name: cache
        path: /cache

  - name: npm-install
    image: node:10
    commands:
      - npm config set cache ./.npm-cache --global
      - npm config set registry http://registry.npm.taobao.org/
      - npm install && npm run build:$PROFILE

  - name: rebuild-cache
    image: drillster/drone-volume-cache
    settings:
      rebuild: true
      mount:
        - ./.npm-cache
        - ./node_modules
    volumes:
      - name: cache
        path: /cache

  - name: build
    image: plugins/docker
    settings:
      mirror: https://hccwwfjl.mirror.aliyuncs.com/
      registry: swr.cn-north-1.myhuaweicloud.com
      username: cn-north-1@8BKNSGZGCNYMTOUZR9YS
      password: e119c7e6f7a4572454fa96f7b8b6fa34d37a00e7e16caa3274b69c0c6eeded7b
      repo: swr.cn-north-1.myhuaweicloud.com/a82253452/${DRONE_STAGE_NAME}/${DRONE_BRANCH}
      tags: ${DRONE_BUILD_NUMBER}
      add-host: localhost:192.168.0.2
      build_args:
        - APPDIR
        - PORT

  - name: release
    image: docker:dind
    environment:
      IMAGE: swr.cn-north-1.myhuaweicloud.com/a82253452/${DRONE_STAGE_NAME}/${DRONE_BRANCH}:${DRONE_BUILD_NUMBER}
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
      - name: registry-auth
        path: /root/.docker
    commands:
      - docker service update --image swr.cn-north-1.myhuaweicloud.com/a82253452/${DRONE_STAGE_NAME}/${DRONE_BRANCH}:${DRONE_BUILD_NUMBER} ${DRONE_STAGE_NAME}-${DRONE_BRANCH}_service --with-registry-auth

  - name: release-failed
    image: docker:dind
    environment:
      IMAGE: swr.cn-north-1.myhuaweicloud.com/a82253452/${DRONE_STAGE_NAME}/${DRONE_BRANCH}:${DRONE_BUILD_NUMBER}
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
      - name: registry-auth
        path: /root/.docker
    when:
      status:
        - failure
    commands:
      - docker stack deploy -c docker-compose.yml ${DRONE_STAGE_NAME}-${DRONE_BRANCH} --with-registry-auth

  - name: dingtalk
    image: lddsb/drone-dingtalk-message
    settings:
      token: https://oapi.dingtalk.com/robot/send?access_token=8231ca915f3e42b623b4a28e0ae6e5ca99861e6553770900eab4be898386cc18
      type: markdown
      message_color: true
      message_pic: true
      sha_link: true
trigger:
  branch:
    - master

volumes:
  - name: cache
    host:
      path: /tmp/cache
  - name: dockersock
    host:
      path: /var/run/docker.sock
  - name: registry-auth
    host:
      path: /root/.docker

---
kind: pipeline
name: mass-page-test

environment:
  DOMAIN: test-ware.zhihuizhan.net
  PATHPREFIX:
  PROFILE: test
  APPDIR: dist
  PORT: 80

steps:

  - name: restore-cache
    image: drillster/drone-volume-cache
    settings:
      restore: true
      mount:
        - ./.npm-cache
        - ./node_modules
    volumes:
      - name: cache
        path: /cache

  - name: npm-install
    image: node:10
    commands:
      - npm config set cache ./.npm-cache --global
      - npm config set registry http://registry.npm.taobao.org/
      - npm install && npm run build:$PROFILE

  - name: rebuild-cache
    image: drillster/drone-volume-cache
    settings:
      rebuild: true
      mount:
        - ./.npm-cache
        - ./node_modules
    volumes:
      - name: cache
        path: /cache

  - name: build
    image: plugins/docker
    settings:
      mirror: https://hccwwfjl.mirror.aliyuncs.com/
      registry: swr.cn-north-1.myhuaweicloud.com
      username: cn-north-1@8BKNSGZGCNYMTOUZR9YS
      password: e119c7e6f7a4572454fa96f7b8b6fa34d37a00e7e16caa3274b69c0c6eeded7b
      repo: swr.cn-north-1.myhuaweicloud.com/a82253452/${DRONE_STAGE_NAME}/${DRONE_BRANCH}
      tags: ${DRONE_BUILD_NUMBER}
      add-host: localhost:192.168.0.2
      build_args:
        - APPDIR
        - PORT

  - name: release
    image: docker:dind
    environment:
      IMAGE: swr.cn-north-1.myhuaweicloud.com/a82253452/${DRONE_STAGE_NAME}/${DRONE_BRANCH}:${DRONE_BUILD_NUMBER}
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
      - name: registry-auth
        path: /root/.docker
    commands:
      - docker service update --image swr.cn-north-1.myhuaweicloud.com/a82253452/${DRONE_STAGE_NAME}/${DRONE_BRANCH}:${DRONE_BUILD_NUMBER} ${DRONE_STAGE_NAME}-${DRONE_BRANCH}_service --with-registry-auth

  - name: release-failed
    image: docker:dind
    environment:
      IMAGE: swr.cn-north-1.myhuaweicloud.com/a82253452/${DRONE_STAGE_NAME}/${DRONE_BRANCH}:${DRONE_BUILD_NUMBER}
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
      - name: registry-auth
        path: /root/.docker
    when:
      status:
        - failure
    commands:
      - docker stack deploy -c docker-compose.yml ${DRONE_STAGE_NAME}-${DRONE_BRANCH} --with-registry-auth

  - name: dingtalk
    image: lddsb/drone-dingtalk-message
    settings:
      token: https://oapi.dingtalk.com/robot/send?access_token=8231ca915f3e42b623b4a28e0ae6e5ca99861e6553770900eab4be898386cc18
      type: markdown
      message_color: true
      message_pic: true
      sha_link: true

trigger:
  branch:
    - test

volumes:
  - name: cache
    host:
      path: /tmp/cache
  - name: dockersock
    host:
      path: /var/run/docker.sock
  - name: registry-auth
    host:
      path: /root/.docker
