kind: pipeline
name: ware-page

trigger:
  branch:
    - master

environment:
  DOMAIN: ware.zhihuizhan.net
  PROFILE: prod
  PORT: 80

steps:

  - name: restore-cache
    image: drillster/drone-volume-cache
    settings:
      restore: true
      mount:
        - ./.npm-cache
        - ./node_modules
    volumes:
      - name: cache
        path: /cache

  - name: npm-install
    image: node:10
    commands:
      - npm config set cache ./.npm-cache --global
      - npm install

  - name: build-dist
    image: node:10
    commands:
      - npm run build

  - name: rebuild-cache
    image: drillster/drone-volume-cache
    settings:
      rebuild: true
      mount:
        - ./.npm-cache
        - ./node_modules
    volumes:
      - name: cache
        path: /cache


  - name: build
    image: plugins/docker
    settings:
      mirror: https://hccwwfjl.mirror.aliyuncs.com/
      registry: swr.cn-north-1.myhuaweicloud.com
      username: cn-north-1@8BKNSGZGCNYMTOUZR9YS
      password: e119c7e6f7a4572454fa96f7b8b6fa34d37a00e7e16caa3274b69c0c6eeded7b
      repo: swr.cn-north-1.myhuaweicloud.com/a82253452/${DRONE_STAGE_NAME}/${DRONE_BRANCH}
      tags: ${DRONE_BUILD_NUMBER}
      build_args:
        - APPDIR=dist

  - name: release
    image: docker:dind
    privileged: true
    environment:
      IMAGE: swr.cn-north-1.myhuaweicloud.com/a82253452/${DRONE_STAGE_NAME}/${DRONE_BRANCH}:${DRONE_BUILD_NUMBER}
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
      - name: registry-auth
        path: /root/.docker
    commands:
      - docker service update --image swr.cn-north-1.myhuaweicloud.com/a82253452/${DRONE_STAGE_NAME}/${DRONE_BRANCH}:${DRONE_BUILD_NUMBER} ${DRONE_STAGE_NAME}-${DRONE_BRANCH}_service --with-registry-auth

  - name: release-failed
    image: docker:dind
    privileged: true
    environment:
      IMAGE: swr.cn-north-1.myhuaweicloud.com/a82253452/${DRONE_STAGE_NAME}/${DRONE_BRANCH}:${DRONE_BUILD_NUMBER}
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
      - name: registry-auth
        path: /root/.docker
    when:
      status:
        - failure
    commands:
      - docker stack deploy -c docker-compose.yml ${DRONE_STAGE_NAME}-${DRONE_BRANCH} --with-registry-auth

volumes:
  - name: cache
    host:
      path: /tmp/cache
  - name: dockersock
    host:
      path: /var/run/docker.sock
  - name: registry-auth
    host:
      path: /root/.docker

kind: pipeline
name: test-ware-page
trigger:
  branch:
    - test

environment:
  DOMAIN: test-ware.zhihuizhan.net
  PROFILE: test
  PORT: 80

steps:

  - name: restore-cache
    image: drillster/drone-volume-cache
    settings:
      restore: true
      mount:
        - ./.npm-cache
        - ./node_modules
    volumes:
      - name: cache
        path: /cache
  - name: npm-install
    image: node:10
    commands:
      - npm config set cache ./.npm-cache --global
      - npm install

  - name: build-dist
    image: node:10
    commands:
      - npm run build

  - name: rebuild-cache
    image: drillster/drone-volume-cache
    settings:
      rebuild: true
      mount:
        - ./.npm-cache
        - ./node_modules
    volumes:
      - name: cache
        path: /cache


  - name: build
    image: plugins/docker
    settings:
      mirror: https://hccwwfjl.mirror.aliyuncs.com/
      registry: swr.cn-north-1.myhuaweicloud.com
      username: cn-north-1@8BKNSGZGCNYMTOUZR9YS
      password: e119c7e6f7a4572454fa96f7b8b6fa34d37a00e7e16caa3274b69c0c6eeded7b
      repo: swr.cn-north-1.myhuaweicloud.com/a82253452/${DRONE_STAGE_NAME}/${DRONE_BRANCH}
      tags: ${DRONE_BUILD_NUMBER}
      build_args:
        - APPDIR=dist

  - name: release
    image: docker:dind
    privileged: true
    environment:
      IMAGE: swr.cn-north-1.myhuaweicloud.com/a82253452/${DRONE_STAGE_NAME}/${DRONE_BRANCH}:${DRONE_BUILD_NUMBER}
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
      - name: registry-auth
        path: /root/.docker
    commands:
      - docker service update --image swr.cn-north-1.myhuaweicloud.com/a82253452/${DRONE_STAGE_NAME}/${DRONE_BRANCH}:${DRONE_BUILD_NUMBER} ${DRONE_STAGE_NAME}-${DRONE_BRANCH}_service --with-registry-auth

  - name: release-failed
    image: docker:dind
    privileged: true
    environment:
      IMAGE: swr.cn-north-1.myhuaweicloud.com/a82253452/${DRONE_STAGE_NAME}/${DRONE_BRANCH}:${DRONE_BUILD_NUMBER}
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
      - name: registry-auth
        path: /root/.docker
    when:
      status:
        - failure
    commands:
      - docker stack deploy -c docker-compose.yml ${DRONE_STAGE_NAME}-${DRONE_BRANCH} --with-registry-auth

volumes:
  - name: cache
    host:
      path: /tmp/cache
  - name: dockersock
    host:
      path: /var/run/docker.sock
  - name: registry-auth
    host:
      path: /root/.docker
