version: "3"
networks:
  default:
    external:
      name: swarm-net
services:
  service:
    image: ${IMAGE}
    deploy:
      resources:
        limits:
          memory: 500M
        reservations:
          memory: 500M
      labels:
        - traefik.http.routers.${DRONE_STAGE_NAME}-${DRONE_BRANCH}-http.rule=Host(`${DOMAIN}`)
        - traefik.http.services.${DRONE_STAGE_NAME}-${DRONE_BRANCH}-http.loadbalancer.server.port=${PORT}

        - traefik.http.routers.${DRONE_STAGE_NAME}-${DRONE_BRANCH}-https.rule=Host(`${DOMAIN}`)
        - traefik.http.routers.${DRONE_STAGE_NAME}-${DRONE_BRANCH}-https.tls.certresolver=mytlschallenge
    environment:
      SPRING_PROFILES_ACTIVE: ${PROFILE}
      PORT: ${PORT}
    volumes:
      - /etc/localtime:/etc/localtime
