version: "3"
networks:
  default:
    external:
      name: swarm-net
services:
  service:
    image: ${IMAGE}
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 500M
        reservations:
          cpus: '0.25'
          memory: 500M
      labels:
        - traefik.http.routers.${DRONE_STAGE_NAME}-${DRONE_BRANCH}-http.rule=Host(`${DOMAIN}`)&& PathPrefix(`/api`)
        - traefik.http.services.${DRONE_STAGE_NAME}-${DRONE_BRANCH}-http.loadbalancer.server.port=${PORT}

        - traefik.http.routers.${DRONE_STAGE_NAME}-${DRONE_BRANCH}-https.rule=Host(`${DOMAIN}`)&& PathPrefix(`/api`)
        - traefik.http.routers.${DRONE_STAGE_NAME}-${DRONE_BRANCH}-https.tls.certresolver=mytlschallenge
        - traefik.http.services.${DRONE_STAGE_NAME}-${DRONE_BRANCH}-https.loadbalancer.server.port=${PORT}
        - traefik.http.middlewares.strip-prefix-api.stripprefix.prefixes=/api
        - traefik.http.routers.${DRONE_STAGE_NAME}-${DRONE_BRANCH}-http.middlewares=strip-prefix-api@docker
        - traefik.http.routers.${DRONE_STAGE_NAME}-${DRONE_BRANCH}-https.middlewares=strip-prefix-api@docker
    environment:
      SPRING_PROFILES_ACTIVE: ${PROFILE}
      PORT: ${PORT}
    volumes:
      - /etc/localtime:/etc/localtime
